# Generated by Django 5.1.4 on 2024-12-11 17:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=100, null=True, unique=True)),
                ("password", models.CharField(max_length=255)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "管理员"),
                            ("teacher", "教师"),
                            ("student", "学生"),
                        ],
                        default="student",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                ("CourseID", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=100)),
                ("Description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Administrator",
            fields=[
                ("AdminID", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(default="admin", max_length=50)),
                ("Email", models.EmailField(max_length=100, null=True)),
                ("Password", models.CharField(max_length=255)),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OperationLog",
            fields=[
                ("LogID", models.AutoField(primary_key=True, serialize=False)),
                ("Operation", models.CharField(max_length=200)),
                ("Details", models.TextField()),
                ("Timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "AdminID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operation_logs",
                        to="users.administrator",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                ("QuestionID", models.AutoField(primary_key=True, serialize=False)),
                ("Title", models.CharField(max_length=100)),
                ("Content", models.TextField()),
                ("ScoringCriteria", models.TextField(blank=True, null=True)),
                ("Prompt", models.TextField(blank=True, null=True)),
                ("CreatedAt", models.DateTimeField(default=django.utils.timezone.now)),
                ("IsOpen", models.BooleanField(default=False)),
                ("OpenAt", models.DateTimeField(blank=True, null=True)),
                (
                    "CourseID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="users.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                ("StudentID", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=50)),
                ("Email", models.EmailField(max_length=100, null=True)),
                ("Password", models.CharField(max_length=255)),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentAnswer",
            fields=[
                ("AnswerID", models.AutoField(primary_key=True, serialize=False)),
                ("Content", models.TextField()),
                (
                    "SubmittedAt",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("ConfirmedAt", models.DateTimeField(blank=True, null=True)),
                (
                    "QuestionID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="users.question",
                    ),
                ),
                (
                    "StudentID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="users.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScoringFeedback",
            fields=[
                ("FeedbackID", models.AutoField(primary_key=True, serialize=False)),
                ("Score", models.FloatField()),
                ("Feedback", models.TextField(blank=True, null=True)),
                ("CreatedAt", models.DateTimeField(default=django.utils.timezone.now)),
                ("IsFinal", models.BooleanField(default=False)),
                (
                    "AnswerID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="users.studentanswer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                ("TeacherID", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=50)),
                ("Email", models.EmailField(max_length=100, null=True)),
                ("Password", models.CharField(max_length=255)),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="course",
            name="TeacherID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="users.teacher",
            ),
        ),
        migrations.CreateModel(
            name="APIKey",
            fields=[
                ("KeyID", models.AutoField(primary_key=True, serialize=False)),
                ("Model", models.CharField(max_length=50)),
                ("Version", models.CharField(max_length=20)),
                ("KeyValue", models.CharField(max_length=255)),
                ("Status", models.BooleanField(default=True)),
                (
                    "TeacherID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to="users.teacher",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "CourseID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_courses",
                        to="users.course",
                    ),
                ),
                (
                    "StudentID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_courses",
                        to="users.student",
                    ),
                ),
            ],
            options={
                "unique_together": {("StudentID", "CourseID")},
            },
        ),
    ]
