# Generated by Django 5.1.4 on 2024-12-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_remove_administrator_user_remove_student_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentanswer",
            name="Content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
