# Generated by Django 5.1.4 on 2024-12-16 00:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_studentanswer_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="administrator",
            name="Email",
            field=models.EmailField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="Email",
            field=models.EmailField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="Email",
            field=models.EmailField(max_length=100, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name="administrator",
            index=models.Index(fields=["Email"], name="idx_admin_email"),
        ),
        migrations.AddIndex(
            model_name="apikey",
            index=models.Index(
                fields=["TeacherID", "Status"], name="idx_apikey_teacher_status"
            ),
        ),
        migrations.AddIndex(
            model_name="apikey",
            index=models.Index(
                fields=["Model", "Version"], name="idx_apikey_model_version"
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["TeacherID"], name="idx_course_teacher"),
        ),
        migrations.AddIndex(
            model_name="operationlog",
            index=models.Index(fields=["Timestamp"], name="idx_log_timestamp"),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["CourseID", "IsOpen"], name="idx_question_course_open"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(fields=["CreatedAt"], name="idx_question_created_at"),
        ),
        migrations.AddIndex(
            model_name="scoringfeedback",
            index=models.Index(
                fields=["AnswerID", "IsFinal"], name="idx_feedback_answer_final"
            ),
        ),
        migrations.AddIndex(
            model_name="scoringfeedback",
            index=models.Index(fields=["CreatedAt"], name="idx_feedback_created_at"),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["Email"], name="idx_student_email"),
        ),
        migrations.AddIndex(
            model_name="studentanswer",
            index=models.Index(
                fields=["QuestionID", "StudentID"], name="idx_answer_question_student"
            ),
        ),
        migrations.AddIndex(
            model_name="studentanswer",
            index=models.Index(fields=["SubmittedAt"], name="idx_answer_submitted_at"),
        ),
        migrations.AddIndex(
            model_name="studentcourse",
            index=models.Index(
                fields=["StudentID", "CourseID"], name="idx_student_course"
            ),
        ),
        migrations.AddIndex(
            model_name="teacher",
            index=models.Index(fields=["Email"], name="idx_teacher_email"),
        ),
        migrations.AlterModelTable(
            name="administrator",
            table="Administrator",
        ),
        migrations.AlterModelTable(
            name="apikey",
            table="APIKey",
        ),
        migrations.AlterModelTable(
            name="course",
            table="Course",
        ),
        migrations.AlterModelTable(
            name="operationlog",
            table="OperationLog",
        ),
        migrations.AlterModelTable(
            name="question",
            table="Question",
        ),
        migrations.AlterModelTable(
            name="scoringfeedback",
            table="ScoringFeedback",
        ),
        migrations.AlterModelTable(
            name="student",
            table="Student",
        ),
        migrations.AlterModelTable(
            name="studentanswer",
            table="StudentAnswer",
        ),
        migrations.AlterModelTable(
            name="studentcourse",
            table="StudentCourse",
        ),
        migrations.AlterModelTable(
            name="teacher",
            table="Teacher",
        ),
    ]
